In [1]:
 %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
catapult_data = pd.read_csv(os.path.join('data_csv', 'catapult_data', 'athlete_load_data_master_v1.csv'))
catapult_data.head()

,id,date,Jersey,total_ima,ima_high_avg,ima_high_total,ima_medium_total,ima_low_total,ima_per_min,ima_accel_high,...,rhie_bout_recovery_mean,rhie_effort_duration_max,rhie_effort_duration_min,rhie_effort_duration_max.1,rhie_effort_per_bout,rhie_effort_per_bout_max,rhie_effort_recovery_min,rhie_effort_recovery_mean,rhie_total_bouts,rhie_efforts_per_bout_min
0,bc83f44d-fdf4-42a7-a23b-565de107bb9c,5/24/2016,4,713,73,73,136,504,10,13,...,83.0,0:00:00,0:00:00,0.0,7.0,17.0,0.0,3.0,37.0,3.0
1,bc83f44d-fdf4-42a7-a23b-565de107bb9c,5/25/2016,4,420,20,20,64,336,6,2,...,192.0,0:00:00,0:00:00,0.0,13.0,24.0,0.0,3.0,15.0,0.0
2,bc83f44d-fdf4-42a7-a23b-565de107bb9c,5/26/2016,4,436,30,30,79,327,6,13,...,140.0,0:00:00,0:00:00,0.0,6.0,14.0,0.0,4.0,21.0,0.0
3,bc83f44d-fdf4-42a7-a23b-565de107bb9c,6/21/2016,4,1070,98,98,207,765,7,14,...,104.0,0:00:00,0:00:00,0.0,6.0,16.0,0.0,2.0,34.0,0.0
4,bc83f44d-fdf4-42a7-a23b-565de107bb9c,6/23/2016,4,1027,83,83,177,767,9,18,...,83.0,0:00:00,0:00:00,0.0,5.0,13.0,0.0,3.0,35.0,0.0

In [7]:
injury_data = pd.read_csv(os.path.join('data_csv','injury_report_2.csv'))
injury_data.head()

,injury_date,id,type,history,onset,tissue,onset_2,osics_diagnosis,body_area,injury_side,injury_aspect,body_region,injury_diagnosis,diagnosis_summary,initial_table_pain_rating,final_table_pain_rating,date_to_limited_full_tolerated,total_tx,injury
0,10/31/2016,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Injury,New,Acute,soft tissue,overuse,Right Knee KTQT Quadriceps tendinopathy,Knee,Right,Anterior,Knee/Lower leg,Quadriceps tendinopathy,Right Knee KTQT Quadriceps tendinopathy,4.0,1.0,5.0,49.0,1
1,7/21/2017,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Problem,NaN,NaN,soft tissue,overuse,Left Thoracic Spine DMXX Thoracic Muscle and T...,Thoracic Spine,Left,Posterior,Thoracic/Side/Chest,Thoracic Muscle and Tendon Strain/ Spasm/ Trig...,Left Thoracic Spine DMXX Thoracic Muscle and T...,NaN,NaN,3.0,4.0,1
2,10/5/2017,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Injury,NaN,NaN,soft tissue,overuse,Left Hip and Groin GMFX Hip flexor muscle stra...,Hip and Groin,Left,Anterior,Hip/Groin/Thigh,Hip flexor muscle strain/ tear,Left Hip and Groin GMFX Hip flexor muscle stra...,NaN,NaN,1.0,42.0,1
3,4/3/2018,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Injury,Recurrent,Chronic,soft tissue,overuse,NaN,Knee,Right,Anterior,Knee/Lower leg,Quadriceps tendinopathy,Right Knee KTQT Quadriceps tendinopathy,NaN,NaN,NaN,NaN,1
4,6/19/2017,f7964398-11c7-4287-9578-2698d6240e00,Injury,New,Chronic,hard tissue,insidious,Lumbar Spine LZZX Lumbar pain undiagnosed,Lumbar Spine,NaN,Posterior,Lumbar/Pelvis/Abd/Buttock,Lumbar pain undiagnosed,Lumbar Spine LZZX Lumbar pain undiagnosed,NaN,NaN,36.0,12.0,1

In [4]:
catapult_practice = catapult_data[2675:2685]
catapult_practice

,id,date,Jersey,total_ima,ima_high_avg,ima_high_total,ima_medium_total,ima_low_total,ima_per_min,ima_accel_high,...,rhie_bout_recovery_mean,rhie_effort_duration_max,rhie_effort_duration_min,rhie_effort_duration_max.1,rhie_effort_per_bout,rhie_effort_per_bout_max,rhie_effort_recovery_min,rhie_effort_recovery_mean,rhie_total_bouts,rhie_efforts_per_bout_min
2675,6f8b7570-63e2-499a-85ac-e3cf1bd56022,10/29/2016,35,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2676,6f8b7570-63e2-499a-85ac-e3cf1bd56022,10/31/2016,35,1117,66,66,207,844,9,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2677,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/1/2016,35,895,50,50,138,707,7,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2678,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/3/2016,35,922,41,41,149,732,7,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2679,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/4/2016,35,684,49,49,97,538,5,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2680,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/7/2016,35,870,52,52,134,684,8,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2681,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/8/2016,35,1319,69,69,238,1012,8,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2682,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/9/2016,35,3,2,2,0,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2683,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/10/2016,35,674,35,35,100,539,8,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2684,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/11/2016,35,480,37,37,65,378,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
injury_practice = injury_data[0:5]
injury_practice

,injury_date,id,type,history,onset,tissue,onset_2,osics_diagnosis,body_area,injury_side,injury_aspect,body_region,injury_diagnosis,diagnosis_summary,initial_table_pain_rating,final_table_pain_rating,date_to_limited_full_tolerated,total_tx,injury
0,10/31/2016,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Injury,New,Acute,soft tissue,overuse,Right Knee KTQT Quadriceps tendinopathy,Knee,Right,Anterior,Knee/Lower leg,Quadriceps tendinopathy,Right Knee KTQT Quadriceps tendinopathy,4.0,1.0,5.0,49.0,1
1,7/21/2017,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Problem,NaN,NaN,soft tissue,overuse,Left Thoracic Spine DMXX Thoracic Muscle and T...,Thoracic Spine,Left,Posterior,Thoracic/Side/Chest,Thoracic Muscle and Tendon Strain/ Spasm/ Trig...,Left Thoracic Spine DMXX Thoracic Muscle and T...,NaN,NaN,3.0,4.0,1
2,10/5/2017,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Injury,NaN,NaN,soft tissue,overuse,Left Hip and Groin GMFX Hip flexor muscle stra...,Hip and Groin,Left,Anterior,Hip/Groin/Thigh,Hip flexor muscle strain/ tear,Left Hip and Groin GMFX Hip flexor muscle stra...,NaN,NaN,1.0,42.0,1
3,4/3/2018,6f8b7570-63e2-499a-85ac-e3cf1bd56022,Injury,Recurrent,Chronic,soft tissue,overuse,NaN,Knee,Right,Anterior,Knee/Lower leg,Quadriceps tendinopathy,Right Knee KTQT Quadriceps tendinopathy,NaN,NaN,NaN,NaN,1
4,6/19/2017,f7964398-11c7-4287-9578-2698d6240e00,Injury,New,Chronic,hard tissue,insidious,Lumbar Spine LZZX Lumbar pain undiagnosed,Lumbar Spine,NaN,Posterior,Lumbar/Pelvis/Abd/Buttock,Lumbar pain undiagnosed,Lumbar Spine LZZX Lumbar pain undiagnosed,NaN,NaN,36.0,12.0,1

In [6]:
df = pd.merge(catapult_practice, injury_practice, 
              how='left', left_on=['id', 'date'], 
              right_on=['id', 'injury_date'], left_index=False, 
              right_index=False, sort=False, suffixes=('_x', '_y'), 
              copy=True, indicator=False)

#df["injury"].sum()
df

,id,date,Jersey,total_ima,ima_high_avg,ima_high_total,ima_medium_total,ima_low_total,ima_per_min,ima_accel_high,...,injury_side,injury_aspect,body_region,injury_diagnosis,diagnosis_summary,initial_table_pain_rating,final_table_pain_rating,date_to_limited_full_tolerated,total_tx,injury
0,6f8b7570-63e2-499a-85ac-e3cf1bd56022,10/29/2016,35,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6f8b7570-63e2-499a-85ac-e3cf1bd56022,10/31/2016,35,1117,66,66,207,844,9,5,...,Right,Anterior,Knee/Lower leg,Quadriceps tendinopathy,Right Knee KTQT Quadriceps tendinopathy,4.0,1.0,5.0,49.0,1.0
2,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/1/2016,35,895,50,50,138,707,7,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/3/2016,35,922,41,41,149,732,7,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/4/2016,35,684,49,49,97,538,5,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/7/2016,35,870,52,52,134,684,8,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/8/2016,35,1319,69,69,238,1012,8,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/9/2016,35,3,2,2,0,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/10/2016,35,674,35,35,100,539,8,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/11/2016,35,480,37,37,65,378,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
catapult_practice.iloc[1]['date']

'10/31/2016'

In [10]:
injury_practice.iloc[0]['injury_date']

'10/31/2016'

In [11]:
df = df.fillna(value = 0)
pd.set_option('display.max_rows', None)
df

,id,date,Jersey,total_ima,ima_high_avg,ima_high_total,ima_medium_total,ima_low_total,ima_per_min,ima_accel_high,...,injury_side,injury_aspect,body_region,injury_diagnosis,diagnosis_summary,initial_table_pain_rating,final_table_pain_rating,date_to_limited_full_tolerated,total_tx,injury
0,6f8b7570-63e2-499a-85ac-e3cf1bd56022,10/29/2016,35,0,0,0,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
1,6f8b7570-63e2-499a-85ac-e3cf1bd56022,10/31/2016,35,1117,66,66,207,844,9,5,...,Right,Anterior,Knee/Lower leg,Quadriceps tendinopathy,Right Knee KTQT Quadriceps tendinopathy,4.0,1.0,5.0,49.0,1.0
2,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/1/2016,35,895,50,50,138,707,7,5,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/3/2016,35,922,41,41,149,732,7,9,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
4,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/4/2016,35,684,49,49,97,538,5,9,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
5,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/7/2016,35,870,52,52,134,684,8,7,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
6,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/8/2016,35,1319,69,69,238,1012,8,8,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
7,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/9/2016,35,3,2,2,0,1,1,0,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
8,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/10/2016,35,674,35,35,100,539,8,5,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
9,6f8b7570-63e2-499a-85ac-e3cf1bd56022,11/11/2016,35,480,37,37,65,378,3,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0

In [12]:
df['final_table_pain_rating'].mean()

0.1

In [ ]:
df.dtypes

In [ ]:
df = df.drop(['id', 'rhie_effort_duration_max.1', 'date','average_duration','rhie_effort_duration_max', 'rhie_effort_duration_min', 'injury_date'], axis=1)

In [ ]:
#df[['date','average_duration','rhie_effort_duration_max', 'rhie_effort_duration_min']] = df[['date','average_duration','rhie_effort_duration_max', 'rhie_effort_duration_min']].apply(pd.to_datetime)

In [ ]:
#df.dtypes

In [13]:
X = df.drop("injury", axis=1)
y = df["injury"]
print(X.shape, y.shape)

(10, 55) (10,)

In [14]:
 data = X.copy()

data_binary_encoded = pd.get_dummies(df)
data_binary_encoded.head()

,Jersey,total_ima,ima_high_avg,ima_high_total,ima_medium_total,ima_low_total,ima_per_min,ima_accel_high,ima_acel_medium,ima_acel_low,...,injury_side_0,injury_side_Right,injury_aspect_0,injury_aspect_Anterior,body_region_0,body_region_Knee/Lower leg,injury_diagnosis_0,injury_diagnosis_Quadriceps tendinopathy,diagnosis_summary_0,diagnosis_summary_Right Knee KTQT Quadriceps tendinopathy
0,35,0,0,0,0,0,0,0,0,0,...,1,0,1,0,1,0,1,0,1,0
1,35,1117,66,66,207,844,9,5,8,58,...,0,1,0,1,0,1,0,1,0,1
2,35,895,50,50,138,707,7,5,6,34,...,1,0,1,0,1,0,1,0,1,0
3,35,922,41,41,149,732,7,9,9,37,...,1,0,1,0,1,0,1,0,1,0
4,35,684,49,49,97,538,5,9,14,49,...,1,0,1,0,1,0,1,0,1,0

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

In [ ]:
classifier.fit(X_train, y_train)